[package]
name = "passwords"
version = "0.2.0"
authors = ["Brendon Oleary <brendon.oleary@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
Inflector = "0.11.4"
rand = "0.8.0"
structopt = { version = "0.3", default-features = false }
